// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEPV_Api.Models.PMS;

public partial class Departments
{
    public int Id { get; set; }

    public short BookId { get; set; }

    public string DeptName { get; set; }

    public int? ManagerId { get; set; }

    public string Description { get; set; }

    public virtual SetOfBooks Book { get; set; }

    public virtual ICollection<LeaveApplications> LeaveApplications { get; set; } = new List<LeaveApplications>();

    public virtual ICollection<LoginInfo> LoginInfo { get; set; } = new List<LoginInfo>();

    public virtual LoginInfo Manager { get; set; }
}