// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEPV_Api.Models.PMS;

public partial class LoginMenus
{
    public int Id { get; set; }

    public string MenuName { get; set; }

    public string Description { get; set; }

    public string Url { get; set; }

    public int? Parent { get; set; }

    public short SeqNo { get; set; }

    public bool IsNode { get; set; }

    public string Icon { get; set; }

    public virtual ICollection<LoginRolesMenus> LoginRolesMenus { get; set; } = new List<LoginRolesMenus>();
}