// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEPV_Api.Models.PMS;

public partial class LoginRoles
{
    public int Id { get; set; }

    public string RoleName { get; set; }

    public string Description { get; set; }

    public bool Disabled { get; set; }

    public short BookId { get; set; }

    public bool IsAdmin { get; set; }

    public byte PermissionLevel { get; set; }

    public virtual SetOfBooks Book { get; set; }

    public virtual ICollection<LoginInfoRoles> LoginInfoRoles { get; set; } = new List<LoginInfoRoles>();

    public virtual ICollection<LoginRolesMenus> LoginRolesMenus { get; set; } = new List<LoginRolesMenus>();

    public virtual ICollection<Project2Check> Project2Check { get; set; } = new List<Project2Check>();

    public virtual ICollection<ProjectPlm> ProjectPlm { get; set; } = new List<ProjectPlm>();
}