// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEPV_Api.Models.PMS
{
    public partial class LoginInfo
    {
        public LoginInfo()
        {
            Departments = new HashSet<Departments>();
            ExpenseClaims = new HashSet<ExpenseClaims>();
            LeaveApplications = new HashSet<LeaveApplications>();
            LoginInfoRoles = new HashSet<LoginInfoRoles>();
            ProjectSvc = new HashSet<ProjectSvc>();
            ProjectSvcTeam = new HashSet<ProjectSvcTeam>();
        }

        public int Id { get; set; }
        public short BookId { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Description { get; set; }
        public bool Disabled { get; set; }
        public DateTime? JoinedDate { get; set; }
        public int? DeptId { get; set; }

        public virtual SetOfBooks Book { get; set; }
        public virtual ICollection<Departments> Departments { get; set; }
        public virtual ICollection<ExpenseClaims> ExpenseClaims { get; set; }
        public virtual ICollection<LeaveApplications> LeaveApplications { get; set; }
        public virtual ICollection<LoginInfoRoles> LoginInfoRoles { get; set; }
        public virtual ICollection<ProjectSvc> ProjectSvc { get; set; }
        public virtual ICollection<ProjectSvcTeam> ProjectSvcTeam { get; set; }
    }
}