// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace SEPV_Api.Models.PMS
{
    public partial class PMSContext : DbContext
    {
        public PMSContext()
        {
        }

        public PMSContext(DbContextOptions<PMSContext> options)
            : base(options)
        {
        }

        public virtual DbSet<CodeLookup> CodeLookup { get; set; }
        public virtual DbSet<CodeLookupSource> CodeLookupSource { get; set; }
        public virtual DbSet<CustomerPlm> CustomerPlm { get; set; }
        public virtual DbSet<LoginInfo> LoginInfo { get; set; }
        public virtual DbSet<LoginInfoRoles> LoginInfoRoles { get; set; }
        public virtual DbSet<LoginMenus> LoginMenus { get; set; }
        public virtual DbSet<LoginRoles> LoginRoles { get; set; }
        public virtual DbSet<LoginRolesMenus> LoginRolesMenus { get; set; }
        public virtual DbSet<ProjectPlm> ProjectPlm { get; set; }
        public virtual DbSet<SetOfBooks> SetOfBooks { get; set; }
        public virtual DbSet<WeeklyReportPlm> WeeklyReportPlm { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CodeLookup>(entity =>
            {
                entity.HasKey(e => new { e.SourceTable, e.Code });

                entity.ToTable("code_lookup");

                entity.Property(e => e.SourceTable)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("source_table");

                entity.Property(e => e.Code)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("code");

                entity.Property(e => e.Description)
                    .HasMaxLength(50)
                    .HasColumnName("description");

                entity.HasOne(d => d.SourceTableNavigation)
                    .WithMany(p => p.CodeLookup)
                    .HasForeignKey(d => d.SourceTable)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_code_lookup_code_lookup_source");
            });

            modelBuilder.Entity<CodeLookupSource>(entity =>
            {
                entity.HasKey(e => e.SourceTable);

                entity.ToTable("code_lookup_source");

                entity.Property(e => e.SourceTable)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("source_table");

                entity.Property(e => e.Description)
                    .HasMaxLength(50)
                    .HasColumnName("description");
            });

            modelBuilder.Entity<CustomerPlm>(entity =>
            {
                entity.ToTable("CustomerPLM");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Contact)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("contact");

                entity.Property(e => e.Contact2)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("contact2");

                entity.Property(e => e.Contact3)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("contact3");

                entity.Property(e => e.Contact4)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("contact4");

                entity.Property(e => e.Contact5)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("contact5");

                entity.Property(e => e.DecisionLevel)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("decision_level");

                entity.Property(e => e.Description)
                    .HasMaxLength(500)
                    .IsUnicode(false)
                    .HasColumnName("description");

                entity.Property(e => e.ExistingCad)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("existing_cad");

                entity.Property(e => e.ExistingPlm)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("existing_plm");

                entity.Property(e => e.IndustryCrm)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("industry_crm");

                entity.Property(e => e.Name)
                    .HasMaxLength(50)
                    .HasColumnName("name");

                entity.Property(e => e.TaxIdNo).HasColumnName("tax_id_no");

                entity.Property(e => e.Telephone)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("telephone");

                entity.Property(e => e.Telephone2)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("telephone2");

                entity.Property(e => e.Telephone3)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("telephone3");

                entity.Property(e => e.Telephone4)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("telephone4");

                entity.Property(e => e.Telephone5)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("telephone5");
            });

            modelBuilder.Entity<LoginInfo>(entity =>
            {
                entity.ToTable("login_info");

                entity.HasIndex(e => e.Username, "IX_login_info")
                    .IsUnique();

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.BookId).HasColumnName("book_id");

                entity.Property(e => e.Description)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("description");

                entity.Property(e => e.Disabled).HasColumnName("disabled");

                entity.Property(e => e.Password)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("password");

                entity.Property(e => e.Username)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("username");

                entity.HasOne(d => d.Book)
                    .WithMany(p => p.LoginInfo)
                    .HasForeignKey(d => d.BookId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_login_info_set_of_books");
            });

            modelBuilder.Entity<LoginInfoRoles>(entity =>
            {
                entity.ToTable("login_info_roles");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.InfoId).HasColumnName("info_id");

                entity.Property(e => e.RoleId).HasColumnName("role_id");

                entity.HasOne(d => d.Info)
                    .WithMany(p => p.LoginInfoRoles)
                    .HasForeignKey(d => d.InfoId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_login_info_roles_login_info");

                entity.HasOne(d => d.Role)
                    .WithMany(p => p.LoginInfoRoles)
                    .HasForeignKey(d => d.RoleId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_login_info_roles_login_roles");
            });

            modelBuilder.Entity<LoginMenus>(entity =>
            {
                entity.ToTable("login_menus");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Description)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("description");

                entity.Property(e => e.Icon)
                    .HasMaxLength(30)
                    .IsUnicode(false)
                    .HasColumnName("icon");

                entity.Property(e => e.IsNode)
                    .IsRequired()
                    .HasColumnName("isNode")
                    .HasDefaultValueSql("((1))");

                entity.Property(e => e.MenuName)
                    .IsRequired()
                    .HasMaxLength(25)
                    .IsUnicode(false)
                    .HasColumnName("menu_name");

                entity.Property(e => e.Parent).HasColumnName("parent");

                entity.Property(e => e.SeqNo).HasColumnName("seq_no");

                entity.Property(e => e.Url)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("url");
            });

            modelBuilder.Entity<LoginRoles>(entity =>
            {
                entity.ToTable("login_roles");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.BookId).HasColumnName("book_id");

                entity.Property(e => e.Description)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("description");

                entity.Property(e => e.Disabled).HasColumnName("disabled");

                entity.Property(e => e.IsAdmin).HasColumnName("isAdmin");

                entity.Property(e => e.PermissionLevel)
                    .HasColumnName("permission_level")
                    .HasDefaultValueSql("((1))");

                entity.Property(e => e.RoleName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("role_name");

                entity.HasOne(d => d.Book)
                    .WithMany(p => p.LoginRoles)
                    .HasForeignKey(d => d.BookId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_login_roles_set_of_books");
            });

            modelBuilder.Entity<LoginRolesMenus>(entity =>
            {
                entity.ToTable("login_roles_menus");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.MenuId).HasColumnName("menu_id");

                entity.Property(e => e.RoleId).HasColumnName("role_id");

                entity.HasOne(d => d.Menu)
                    .WithMany(p => p.LoginRolesMenus)
                    .HasForeignKey(d => d.MenuId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_login_roles_menus_login_menus");

                entity.HasOne(d => d.Role)
                    .WithMany(p => p.LoginRolesMenus)
                    .HasForeignKey(d => d.RoleId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_login_roles_menus_login_roles");
            });

            modelBuilder.Entity<ProjectPlm>(entity =>
            {
                entity.ToTable("ProjectPLM");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.AgsStatus)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("ags_status");

                entity.Property(e => e.CloseDate)
                    .HasColumnType("date")
                    .HasColumnName("close_date");

                entity.Property(e => e.CreatedAt)
                    .HasColumnType("datetime")
                    .HasColumnName("created_at")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.CustomerId).HasColumnName("customer_id");

                entity.Property(e => e.IsAgsBooking).HasColumnName("is_ags_booking");

                entity.Property(e => e.IsSystemChecked).HasColumnName("is_system_checked");

                entity.Property(e => e.Month).HasColumnName("month");

                entity.Property(e => e.NetToDsAmount)
                    .HasColumnType("decimal(18, 2)")
                    .HasColumnName("net_to_ds_amount");

                entity.Property(e => e.Quarter)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("quarter");

                entity.Property(e => e.RfqToClientAmount)
                    .HasColumnType("decimal(18, 2)")
                    .HasColumnName("rfq_to_client_amount");

                entity.Property(e => e.RoleId).HasColumnName("role_id");

                entity.Property(e => e.SalesOwner).HasColumnName("sales_owner");

                entity.Property(e => e.ServiceOwner).HasColumnName("service_owner");

                entity.Property(e => e.SolutionMapping)
                    .HasMaxLength(300)
                    .IsUnicode(false)
                    .HasColumnName("solution_mapping");

                entity.Property(e => e.SystemInquiryChannel)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("system_inquiry_channel");

                entity.Property(e => e.UnderControlLongshotYearQ)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("under_control_longshot_year_q");

                entity.Property(e => e.UpdatedAt)
                    .HasColumnType("datetime")
                    .HasColumnName("updated_at");

                entity.Property(e => e.Year).HasColumnName("year");

                entity.HasOne(d => d.Customer)
                    .WithMany(p => p.ProjectPlm)
                    .HasForeignKey(d => d.CustomerId)
                    .HasConstraintName("FK_ProjectPLM_CustomerPLM");

                entity.HasOne(d => d.Role)
                    .WithMany(p => p.ProjectPlm)
                    .HasForeignKey(d => d.RoleId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ProjectPLM_login_roles");
            });

            modelBuilder.Entity<SetOfBooks>(entity =>
            {
                entity.HasKey(e => e.BookId);

                entity.ToTable("set_of_books");

                entity.Property(e => e.BookId)
                    .ValueGeneratedNever()
                    .HasColumnName("book_id");

                entity.Property(e => e.Description)
                    .HasMaxLength(250)
                    .IsUnicode(false)
                    .HasColumnName("description");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("name");
            });

            modelBuilder.Entity<WeeklyReportPlm>(entity =>
            {
                entity.ToTable("WeeklyReportPLM");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Content).HasColumnName("content");

                entity.Property(e => e.CreatedAt)
                    .HasColumnType("datetime")
                    .HasColumnName("created_at")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.ProjectId).HasColumnName("project_id");

                entity.Property(e => e.UpdatedAt)
                    .HasColumnType("datetime")
                    .HasColumnName("updated_at");

                entity.Property(e => e.Week).HasColumnName("week");

                entity.Property(e => e.Year).HasColumnName("year");

                entity.HasOne(d => d.Project)
                    .WithMany(p => p.WeeklyReportPlm)
                    .HasForeignKey(d => d.ProjectId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_WeeklyReport_Project");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}