// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEPV_Api.Models.PMS;

public partial class ProjectSvc
{
    public int Id { get; set; }

    public short BookId { get; set; }

    public string ProjectName { get; set; }

    public decimal? ContractAmount { get; set; }

    public int? ProjectManagerId { get; set; }

    public decimal? PlannedDays { get; set; }

    public decimal? ActualDays { get; set; }

    public decimal? MarginPercentage { get; set; }

    public DateTime? SowSignedDate { get; set; }

    public DateTime? KickoffDate { get; set; }

    public DateTime? AccessDate { get; set; }

    public DateTime? DefineDate { get; set; }

    public DateTime? DesignDate { get; set; }

    public DateTime? UatDate { get; set; }

    public DateTime? GoLiveDate { get; set; }

    public DateTime? RolloutDate { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual SetOfBooks Book { get; set; }

    public virtual LoginInfo ProjectManager { get; set; }

    public virtual ICollection<ProjectSvcTeam> ProjectSvcTeam { get; set; } = new List<ProjectSvcTeam>();
}