// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEPV_Api.Models.PMS;

public partial class Project2Check
{
    public int Id { get; set; }

    public int RoleId { get; set; }

    public short BookId { get; set; }

    public int? Year { get; set; }

    public string Quarter { get; set; }

    public int? Month { get; set; }

    public DateTime? CloseDate { get; set; }

    public int? CustomerId { get; set; }

    public string Status { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string Description { get; set; }

    public virtual SetOfBooks Book { get; set; }

    public virtual Customer2Check Customer { get; set; }

    public virtual LoginRoles Role { get; set; }
}