// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEPV_Api.Models.PMS;

public partial class ProjectSvcTeam
{
    public int ProjectSvcId { get; set; }

    public int UserId { get; set; }

    public DateTime? CreatedAt { get; set; }

    public virtual ProjectSvc ProjectSvc { get; set; }

    public virtual LoginInfo User { get; set; }
}