// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEPV_Api.Models.PMS;

public partial class SetOfBooks
{
    public short BookId { get; set; }

    public string Name { get; set; }

    public string Description { get; set; }

    public virtual ICollection<CheckinLogs> CheckinLogs { get; set; } = new List<CheckinLogs>();

    public virtual ICollection<Departments> Departments { get; set; } = new List<Departments>();

    public virtual ICollection<ExpenseClaims> ExpenseClaims { get; set; } = new List<ExpenseClaims>();

    public virtual ICollection<LoginInfo> LoginInfo { get; set; } = new List<LoginInfo>();

    public virtual ICollection<LoginRoles> LoginRoles { get; set; } = new List<LoginRoles>();

    public virtual ICollection<ProjectFirm> ProjectFirm { get; set; } = new List<ProjectFirm>();

    public virtual ICollection<ProjectInternal> ProjectInternal { get; set; } = new List<ProjectInternal>();

    public virtual ICollection<ProjectPlm> ProjectPlm { get; set; } = new List<ProjectPlm>();

    public virtual ICollection<ProjectSvc> ProjectSvc { get; set; } = new List<ProjectSvc>();

    public virtual ICollection<TaskMaster> TaskMaster { get; set; } = new List<TaskMaster>();
}