// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEPV_Api.Models.PMS
{
    public partial class SetOfBooks
    {
        public SetOfBooks()
        {
            CheckinLogs = new HashSet<CheckinLogs>();
            Departments = new HashSet<Departments>();
            ExpenseClaims = new HashSet<ExpenseClaims>();
            LoginInfo = new HashSet<LoginInfo>();
            LoginRoles = new HashSet<LoginRoles>();
            ProjectInternal = new HashSet<ProjectInternal>();
            ProjectPlm = new HashSet<ProjectPlm>();
            ProjectSvc = new HashSet<ProjectSvc>();
            TaskMaster = new HashSet<TaskMaster>();
        }

        public short BookId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        public virtual ICollection<CheckinLogs> CheckinLogs { get; set; }
        public virtual ICollection<Departments> Departments { get; set; }
        public virtual ICollection<ExpenseClaims> ExpenseClaims { get; set; }
        public virtual ICollection<LoginInfo> LoginInfo { get; set; }
        public virtual ICollection<LoginRoles> LoginRoles { get; set; }
        public virtual ICollection<ProjectInternal> ProjectInternal { get; set; }
        public virtual ICollection<ProjectPlm> ProjectPlm { get; set; }
        public virtual ICollection<ProjectSvc> ProjectSvc { get; set; }
        public virtual ICollection<TaskMaster> TaskMaster { get; set; }
    }
}