// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEPV_Api.Models.PMS;

public partial class TaskMaster
{
    public int Id { get; set; }

    public short BookId { get; set; }

    public string TaskName { get; set; }

    public string Description { get; set; }

    public string Category { get; set; }

    public string Priority { get; set; }

    public string Status { get; set; }

    public DateTime? CloseDate { get; set; }

    public DateTime? CreatedAt { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public virtual SetOfBooks Book { get; set; }
}