// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEPV_Api.Models.PMS
{
    public partial class WeeklyReportPlm
    {
        public int Id { get; set; }
        public int ProjectId { get; set; }
        public int Year { get; set; }
        public int Week { get; set; }
        public string Content { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }

        public virtual ProjectPlm Project { get; set; }
    }
}