// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEPV_Api.Models.GreenPower
{
    public partial class BankBranchInfo
    {
        public BankBranchInfo()
        {
            PsbankData = new HashSet<PsbankData>();
        }

        public int Id { get; set; }
        public string BranchNo { get; set; }
        public string BranchName { get; set; }
        public string Description { get; set; }
        public bool Disable { get; set; }
        public int BankId { get; set; }

        public virtual BankInfo Bank { get; set; }
        public virtual ICollection<PsbankData> PsbankData { get; set; }
    }
}