// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEPV_Api.Models.GreenPower
{
    public partial class BankInfo
    {
        public BankInfo()
        {
            BankBranchInfo = new HashSet<BankBranchInfo>();
            PspowerNoInfo = new HashSet<PspowerNoInfo>();
        }

        public int Id { get; set; }
        public string BankNo { get; set; }
        public string BankName { get; set; }
        public string Description { get; set; }
        public bool Disable { get; set; }

        public virtual ICollection<BankBranchInfo> BankBranchInfo { get; set; }
        public virtual ICollection<PspowerNoInfo> PspowerNoInfo { get; set; }
    }
}