// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEPV_Api.Models.GreenPower
{
    public partial class BooksMenus
    {
        public int Id { get; set; }
        public short BookId { get; set; }
        public int MenuId { get; set; }

        public virtual SetOfBooks Book { get; set; }
        public virtual LoginMenus Menu { get; set; }
    }
}