// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace SEPV_Api.Models.GreenPower
{
    public partial class GreenPowerContext : DbContext
    {
        public GreenPowerContext()
        {
        }

        public GreenPowerContext(DbContextOptions<GreenPowerContext> options)
            : base(options)
        {
        }

        public virtual DbSet<BankBranchInfo> BankBranchInfo { get; set; }
        public virtual DbSet<BankInfo> BankInfo { get; set; }
        public virtual DbSet<CodeLookup> CodeLookup { get; set; }
        public virtual DbSet<CodeLookupSource> CodeLookupSource { get; set; }
        public virtual DbSet<CustomerPlm> CustomerPlm { get; set; }
        public virtual DbSet<LoginInfo> LoginInfo { get; set; }
        public virtual DbSet<LoginInfoRoles> LoginInfoRoles { get; set; }
        public virtual DbSet<LoginMenus> LoginMenus { get; set; }
        public virtual DbSet<LoginRoles> LoginRoles { get; set; }
        public virtual DbSet<LoginRolesMenus> LoginRolesMenus { get; set; }
        public virtual DbSet<PpbasicInfo> PpbasicInfo { get; set; }
        public virtual DbSet<PpmeterNoInfo> PpmeterNoInfo { get; set; }
        public virtual DbSet<PppowerNoInfo> PppowerNoInfo { get; set; }
        public virtual DbSet<ProjectPlm> ProjectPlm { get; set; }
        public virtual DbSet<PsbankData> PsbankData { get; set; }
        public virtual DbSet<PsbasicInfo> PsbasicInfo { get; set; }
        public virtual DbSet<PsmeterNoInfo> PsmeterNoInfo { get; set; }
        public virtual DbSet<PspowerNoInfo> PspowerNoInfo { get; set; }
        public virtual DbSet<PssurplusData> PssurplusData { get; set; }
        public virtual DbSet<PssurplusInfo> PssurplusInfo { get; set; }
        public virtual DbSet<ServiceNoDetailData> ServiceNoDetailData { get; set; }
        public virtual DbSet<ServiceNoDetailInfo> ServiceNoDetailInfo { get; set; }
        public virtual DbSet<ServiceNoInfo> ServiceNoInfo { get; set; }
        public virtual DbSet<SetOfBooks> SetOfBooks { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<BankBranchInfo>(entity =>
            {
                entity.ToTable("bank_branch_info");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.BankId).HasColumnName("bank_id");

                entity.Property(e => e.BranchName)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("branch_name");

                entity.Property(e => e.BranchNo)
                    .IsRequired()
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("branch_no");

                entity.Property(e => e.Description)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("description");

                entity.Property(e => e.Disable).HasColumnName("disable");

                entity.HasOne(d => d.Bank)
                    .WithMany(p => p.BankBranchInfo)
                    .HasForeignKey(d => d.BankId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_bank_branch_info_bank_info");
            });

            modelBuilder.Entity<BankInfo>(entity =>
            {
                entity.ToTable("bank_info");

                entity.HasIndex(e => e.BankNo, "IX_bank_info")
                    .IsUnique();

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.BankName)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("bank_name");

                entity.Property(e => e.BankNo)
                    .IsRequired()
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasColumnName("bank_no");

                entity.Property(e => e.Description)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("description");

                entity.Property(e => e.Disable).HasColumnName("disable");
            });

            modelBuilder.Entity<CodeLookup>(entity =>
            {
                entity.HasKey(e => new { e.SourceTable, e.Code });

                entity.ToTable("code_lookup");

                entity.Property(e => e.SourceTable)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("source_table");

                entity.Property(e => e.Code)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("code");

                entity.Property(e => e.Description)
                    .HasMaxLength(50)
                    .HasColumnName("description");

                entity.HasOne(d => d.SourceTableNavigation)
                    .WithMany(p => p.CodeLookup)
                    .HasForeignKey(d => d.SourceTable)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_code_lookup_code_lookup_source");
            });

            modelBuilder.Entity<CodeLookupSource>(entity =>
            {
                entity.HasKey(e => e.SourceTable);

                entity.ToTable("code_lookup_source");

                entity.Property(e => e.SourceTable)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("source_table");

                entity.Property(e => e.Description)
                    .HasMaxLength(50)
                    .HasColumnName("description");
            });

            modelBuilder.Entity<CustomerPlm>(entity =>
            {
                entity.ToTable("CustomerPLM");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Contact)
                    .HasMaxLength(50)
                    .HasColumnName("contact");

                entity.Property(e => e.Contact2)
                    .HasMaxLength(50)
                    .HasColumnName("contact2");

                entity.Property(e => e.Contact3)
                    .HasMaxLength(50)
                    .HasColumnName("contact3");

                entity.Property(e => e.Contact4)
                    .HasMaxLength(50)
                    .HasColumnName("contact4");

                entity.Property(e => e.Contact5)
                    .HasMaxLength(50)
                    .HasColumnName("contact5");

                entity.Property(e => e.DecisionLevel)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("decision_level");

                entity.Property(e => e.Description)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("description");

                entity.Property(e => e.Name)
                    .HasMaxLength(50)
                    .HasColumnName("name");

                entity.Property(e => e.TaxIdNo).HasColumnName("tax_id_no");

                entity.Property(e => e.Telephone)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("telephone");

                entity.Property(e => e.Telephone2)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("telephone2");

                entity.Property(e => e.Telephone3)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("telephone3");

                entity.Property(e => e.Telephone4)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("telephone4");

                entity.Property(e => e.Telephone5)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("telephone5");
            });

            modelBuilder.Entity<LoginInfo>(entity =>
            {
                entity.ToTable("login_info");

                entity.HasIndex(e => e.Username, "IX_login_info")
                    .IsUnique();

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.BookId).HasColumnName("book_id");

                entity.Property(e => e.Description)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("description");

                entity.Property(e => e.Disabled).HasColumnName("disabled");

                entity.Property(e => e.Password)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("password");

                entity.Property(e => e.Username)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("username");

                entity.HasOne(d => d.Book)
                    .WithMany(p => p.LoginInfo)
                    .HasForeignKey(d => d.BookId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_login_info_set_of_books");
            });

            modelBuilder.Entity<LoginInfoRoles>(entity =>
            {
                entity.ToTable("login_info_roles");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.InfoId).HasColumnName("info_id");

                entity.Property(e => e.RoleId).HasColumnName("role_id");

                entity.HasOne(d => d.Info)
                    .WithMany(p => p.LoginInfoRoles)
                    .HasForeignKey(d => d.InfoId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_login_info_roles_login_info");

                entity.HasOne(d => d.Role)
                    .WithMany(p => p.LoginInfoRoles)
                    .HasForeignKey(d => d.RoleId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_login_info_roles_login_roles");
            });

            modelBuilder.Entity<LoginMenus>(entity =>
            {
                entity.ToTable("login_menus");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Description)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("description");

                entity.Property(e => e.Icon)
                    .HasMaxLength(30)
                    .IsUnicode(false)
                    .HasColumnName("icon");

                entity.Property(e => e.IsNode)
                    .IsRequired()
                    .HasColumnName("isNode")
                    .HasDefaultValueSql("((1))");

                entity.Property(e => e.MenuName)
                    .IsRequired()
                    .HasMaxLength(25)
                    .IsUnicode(false)
                    .HasColumnName("menu_name");

                entity.Property(e => e.Parent).HasColumnName("parent");

                entity.Property(e => e.SeqNo).HasColumnName("seq_no");

                entity.Property(e => e.Url)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("url");
            });

            modelBuilder.Entity<LoginRoles>(entity =>
            {
                entity.ToTable("login_roles");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.BookId).HasColumnName("book_id");

                entity.Property(e => e.Description)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("description");

                entity.Property(e => e.Disabled).HasColumnName("disabled");

                entity.Property(e => e.IsAdmin).HasColumnName("isAdmin");

                entity.Property(e => e.PermissionLevel)
                    .HasColumnName("permission_level")
                    .HasDefaultValueSql("((1))");

                entity.Property(e => e.RoleName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("role_name");

                entity.HasOne(d => d.Book)
                    .WithMany(p => p.LoginRoles)
                    .HasForeignKey(d => d.BookId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_login_roles_set_of_books");
            });

            modelBuilder.Entity<LoginRolesMenus>(entity =>
            {
                entity.ToTable("login_roles_menus");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.MenuId).HasColumnName("menu_id");

                entity.Property(e => e.RoleId).HasColumnName("role_id");

                entity.HasOne(d => d.Menu)
                    .WithMany(p => p.LoginRolesMenus)
                    .HasForeignKey(d => d.MenuId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_login_roles_menus_login_menus");

                entity.HasOne(d => d.Role)
                    .WithMany(p => p.LoginRolesMenus)
                    .HasForeignKey(d => d.RoleId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_login_roles_menus_login_roles");
            });

            modelBuilder.Entity<PpbasicInfo>(entity =>
            {
                entity.ToTable("PPBasicInfo");

                entity.HasIndex(e => e.PpNo, "IX_PPBasicInfo")
                    .IsUnique();

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.BookId).HasColumnName("book_id");

                entity.Property(e => e.Contact)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("contact");

                entity.Property(e => e.Ctype)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("ctype");

                entity.Property(e => e.Description)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("description");

                entity.Property(e => e.PpName)
                    .IsRequired()
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("pp_name");

                entity.Property(e => e.PpNo)
                    .IsRequired()
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasColumnName("pp_no");

                entity.Property(e => e.TaxIdNo).HasColumnName("tax_id_no");

                entity.Property(e => e.Telephone)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("telephone");

                entity.HasOne(d => d.Book)
                    .WithMany(p => p.PpbasicInfo)
                    .HasForeignKey(d => d.BookId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_PPBasicInfo_set_of_books");
            });

            modelBuilder.Entity<PpmeterNoInfo>(entity =>
            {
                entity.ToTable("PPMeterNoInfo");

                entity.HasIndex(e => e.MeterNo, "IX_PPMeterNoInfo")
                    .IsUnique();

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Description)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("description");

                entity.Property(e => e.MeterNo)
                    .IsRequired()
                    .HasMaxLength(15)
                    .IsUnicode(false)
                    .HasColumnName("meter_no");

                entity.Property(e => e.PpId).HasColumnName("pp_id");

                entity.HasOne(d => d.Pp)
                    .WithMany(p => p.PpmeterNoInfo)
                    .HasForeignKey(d => d.PpId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_PPMeterNoInfo_PPPowerNoInfo");
            });

            modelBuilder.Entity<PppowerNoInfo>(entity =>
            {
                entity.ToTable("PPPowerNoInfo");

                entity.HasIndex(e => e.PowerNo, "IX_PPPowerNoInfo")
                    .IsUnique();

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Description)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("description");

                entity.Property(e => e.InfoId).HasColumnName("info_id");

                entity.Property(e => e.PowerNo)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("power_no");

                entity.HasOne(d => d.Info)
                    .WithMany(p => p.PppowerNoInfo)
                    .HasForeignKey(d => d.InfoId)
                    .HasConstraintName("FK_PPPowerNoInfo_PPBasicInfo");
            });

            modelBuilder.Entity<ProjectPlm>(entity =>
            {
                entity.ToTable("ProjectPLM");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.AgsStatus)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("ags_status");

                entity.Property(e => e.CloseDate)
                    .HasColumnType("date")
                    .HasColumnName("close_date");

                entity.Property(e => e.CreatedAt)
                    .HasColumnType("datetime")
                    .HasColumnName("created_at")
                    .HasDefaultValueSql("(getdate())");

                entity.Property(e => e.CustomerId).HasColumnName("customer_id");

                entity.Property(e => e.ExistingCad)
                    .HasMaxLength(200)
                    .HasColumnName("existing_cad");

                entity.Property(e => e.ExistingPlm)
                    .HasMaxLength(100)
                    .HasColumnName("existing_plm");

                entity.Property(e => e.IndustryCrm)
                    .HasMaxLength(100)
                    .HasColumnName("industry_crm");

                entity.Property(e => e.IsAgsBooking).HasColumnName("is_ags_booking");

                entity.Property(e => e.IsSystemChecked)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("is_system_checked");

                entity.Property(e => e.Month).HasColumnName("month");

                entity.Property(e => e.NetToDsAmount)
                    .HasColumnType("decimal(18, 2)")
                    .HasColumnName("net_to_ds_amount");

                entity.Property(e => e.Quarter)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("quarter");

                entity.Property(e => e.RfqToClientAmount)
                    .HasColumnType("decimal(18, 2)")
                    .HasColumnName("rfq_to_client_amount");

                entity.Property(e => e.SalesOwner)
                    .HasMaxLength(100)
                    .HasColumnName("sales_owner");

                entity.Property(e => e.ServiceOwner)
                    .HasMaxLength(100)
                    .HasColumnName("service_owner");

                entity.Property(e => e.SolutionMapping)
                    .HasMaxLength(300)
                    .HasColumnName("solution_mapping");

                entity.Property(e => e.SystemInquiryChannel)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("system_inquiry_channel");

                entity.Property(e => e.UnderControlLongshotYearQ)
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("under_control_longshot_year_q");

                entity.Property(e => e.UpdatedAt)
                    .HasColumnType("datetime")
                    .HasColumnName("updated_at");

                entity.Property(e => e.Year).HasColumnName("year");

                entity.HasOne(d => d.Customer)
                    .WithMany(p => p.ProjectPlm)
                    .HasForeignKey(d => d.CustomerId)
                    .HasConstraintName("FK_ProjectPLM_CustomerPLM");
            });

            modelBuilder.Entity<PsbankData>(entity =>
            {
                entity.ToTable("PSBankData");

                entity.HasIndex(e => new { e.InfoId, e.BranchId, e.BankAccountNumber }, "IX_PSBankData")
                    .IsUnique();

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.BankAccountNumber)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("bank_account_number");

                entity.Property(e => e.BranchId).HasColumnName("branch_id");

                entity.Property(e => e.Description)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("description");

                entity.Property(e => e.InfoId).HasColumnName("info_id");

                entity.HasOne(d => d.Branch)
                    .WithMany(p => p.PsbankData)
                    .HasForeignKey(d => d.BranchId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_PSBankData_bank_branch_info");

                entity.HasOne(d => d.Info)
                    .WithMany(p => p.PsbankData)
                    .HasForeignKey(d => d.InfoId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_PSBankData_PSBasicInfo");
            });

            modelBuilder.Entity<PsbasicInfo>(entity =>
            {
                entity.ToTable("PSBasicInfo");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.BookId).HasColumnName("book_id");

                entity.Property(e => e.Contact)
                    .HasMaxLength(50)
                    .HasColumnName("contact");

                entity.Property(e => e.Description)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("description");

                entity.Property(e => e.Email)
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("email");

                entity.Property(e => e.PsName)
                    .HasMaxLength(50)
                    .HasColumnName("ps_name");

                entity.Property(e => e.PsNo)
                    .IsRequired()
                    .HasMaxLength(3)
                    .IsUnicode(false)
                    .HasColumnName("ps_no");

                entity.Property(e => e.TaxIdNo).HasColumnName("tax_id_no");

                entity.Property(e => e.Telephone)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("telephone");

                entity.HasOne(d => d.Book)
                    .WithMany(p => p.PsbasicInfo)
                    .HasForeignKey(d => d.BookId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_PSBasicInfo_set_of_books");
            });

            modelBuilder.Entity<PsmeterNoInfo>(entity =>
            {
                entity.ToTable("PSMeterNoInfo");

                entity.HasIndex(e => e.MeterNo, "IX_PSMeterNoInfo")
                    .IsUnique();

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Description)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("description");

                entity.Property(e => e.MeterNo)
                    .IsRequired()
                    .HasMaxLength(15)
                    .IsUnicode(false)
                    .HasColumnName("meter_no");

                entity.Property(e => e.PsId).HasColumnName("ps_id");

                entity.HasOne(d => d.Ps)
                    .WithMany(p => p.PsmeterNoInfo)
                    .HasForeignKey(d => d.PsId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_PSMeterNoInfo_PSPowerNoInfo");
            });

            modelBuilder.Entity<PspowerNoInfo>(entity =>
            {
                entity.ToTable("PSPowerNoInfo");

                entity.HasIndex(e => e.PowerNo, "IX_PSPowerNoInfo")
                    .IsUnique();

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Address)
                    .HasMaxLength(500)
                    .IsUnicode(false)
                    .HasColumnName("address");

                entity.Property(e => e.Description)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("description");

                entity.Property(e => e.Etype)
                    .HasMaxLength(10)
                    .IsUnicode(false)
                    .HasColumnName("etype");

                entity.Property(e => e.InfoId).HasColumnName("info_id");

                entity.Property(e => e.PowerNo)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("power_no");

                entity.Property(e => e.PsBankId).HasColumnName("ps_bank_id");

                entity.Property(e => e.SiteName)
                    .HasMaxLength(500)
                    .IsUnicode(false)
                    .HasColumnName("site_name");

                entity.Property(e => e.TrustBankId).HasColumnName("trust_bank_id");

                entity.HasOne(d => d.Info)
                    .WithMany(p => p.PspowerNoInfo)
                    .HasForeignKey(d => d.InfoId)
                    .HasConstraintName("FK_PSPowerNoInfo_PSBasicInfo");

                entity.HasOne(d => d.PsBank)
                    .WithMany(p => p.PspowerNoInfo)
                    .HasForeignKey(d => d.PsBankId)
                    .HasConstraintName("FK_PSPowerNoInfo_PSBankData");

                entity.HasOne(d => d.TrustBank)
                    .WithMany(p => p.PspowerNoInfo)
                    .HasForeignKey(d => d.TrustBankId)
                    .HasConstraintName("FK_PSPowerNoInfo_bank_info");
            });

            modelBuilder.Entity<PssurplusData>(entity =>
            {
                entity.ToTable("PSSurplusData");

                entity.HasIndex(e => new { e.SurplusId, e.BillYear, e.BillMonth }, "IX_PSSurplusData")
                    .IsUnique();

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.BillMonth).HasColumnName("bill_month");

                entity.Property(e => e.BillYear).HasColumnName("bill_year");

                entity.Property(e => e.Description)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("description");

                entity.Property(e => e.SurplusAmount).HasColumnName("surplus_amount");

                entity.Property(e => e.SurplusId).HasColumnName("surplus_id");

                entity.Property(e => e.SurplusKwh).HasColumnName("surplus_kwh");

                entity.HasOne(d => d.Surplus)
                    .WithMany(p => p.PssurplusData)
                    .HasForeignKey(d => d.SurplusId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_PSSurplusData_PSSurplusInfo");
            });

            modelBuilder.Entity<PssurplusInfo>(entity =>
            {
                entity.ToTable("PSSurplusInfo");

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Description)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("description");

                entity.Property(e => e.PsId).HasColumnName("ps_id");

                entity.Property(e => e.PsSiteName)
                    .IsRequired()
                    .HasMaxLength(30)
                    .IsUnicode(false)
                    .HasColumnName("ps_site_name");

                entity.Property(e => e.SurplusRate)
                    .HasColumnType("decimal(8, 4)")
                    .HasColumnName("surplus_rate");

                entity.Property(e => e.TotalKwp)
                    .HasColumnType("decimal(18, 3)")
                    .HasColumnName("total_kwp");

                entity.HasOne(d => d.Ps)
                    .WithMany(p => p.PssurplusInfo)
                    .HasForeignKey(d => d.PsId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_PSSurplusPowerNoInfo_PSPowerNoInfo");
            });

            modelBuilder.Entity<ServiceNoDetailData>(entity =>
            {
                entity.HasIndex(e => new { e.ServiceNoDetailId, e.BillYear, e.BillMonth }, "IX_ServiceNoDetailData")
                    .IsUnique();

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.AncillaryServicesRate)
                    .HasColumnType("decimal(8, 4)")
                    .HasColumnName("ancillary_services_rate");

                entity.Property(e => e.BillMonth).HasColumnName("bill_month");

                entity.Property(e => e.BillYear).HasColumnName("bill_year");

                entity.Property(e => e.Description)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("description");

                entity.Property(e => e.DispatchingRate)
                    .HasColumnType("decimal(8, 4)")
                    .HasColumnName("dispatching_rate");

                entity.Property(e => e.DistributionRate)
                    .HasColumnType("decimal(8, 4)")
                    .HasColumnName("distribution_rate");

                entity.Property(e => e.Fee).HasColumnName("fee");

                entity.Property(e => e.KwhUsage).HasColumnName("kwh_usage");

                entity.Property(e => e.ServiceNoDetailId).HasColumnName("service_no_detail_id");

                entity.Property(e => e.TransmissionRate)
                    .HasColumnType("decimal(8, 4)")
                    .HasColumnName("transmission_rate");

                entity.HasOne(d => d.ServiceNoDetail)
                    .WithMany(p => p.ServiceNoDetailData)
                    .HasForeignKey(d => d.ServiceNoDetailId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ServiceNoDetailData_ServiceNoDetailInfo");
            });

            modelBuilder.Entity<ServiceNoDetailInfo>(entity =>
            {
                entity.HasIndex(e => new { e.PpMeterId, e.PsMeterId, e.ServiceNoId }, "IX_ServiceNoDetailInfo")
                    .IsUnique();

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.Description)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("description");

                entity.Property(e => e.PpMeterId).HasColumnName("pp_meter_id");

                entity.Property(e => e.PsMeterId).HasColumnName("ps_meter_id");

                entity.Property(e => e.PsPpPercent)
                    .HasColumnType("decimal(8, 4)")
                    .HasColumnName("ps_pp_percent");

                entity.Property(e => e.PsRate)
                    .HasColumnType("decimal(8, 4)")
                    .HasColumnName("ps_rate");

                entity.Property(e => e.PsTotalKwp)
                    .HasColumnType("decimal(10, 3)")
                    .HasColumnName("ps_total_kwp");

                entity.Property(e => e.ServiceNoId).HasColumnName("service_no_id");

                entity.Property(e => e.Type)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("type");

                entity.HasOne(d => d.PpMeter)
                    .WithMany(p => p.ServiceNoDetailInfo)
                    .HasForeignKey(d => d.PpMeterId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ServiceNoDetailInfo_PPMeterNoInfo");

                entity.HasOne(d => d.PsMeter)
                    .WithMany(p => p.ServiceNoDetailInfo)
                    .HasForeignKey(d => d.PsMeterId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ServiceNoDetailInfo_PSMeterNoInfo");

                entity.HasOne(d => d.ServiceNo)
                    .WithMany(p => p.ServiceNoDetailInfo)
                    .HasForeignKey(d => d.ServiceNoId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ServiceNoDetailInfo_ServiceNoInfo");
            });

            modelBuilder.Entity<ServiceNoInfo>(entity =>
            {
                entity.HasIndex(e => e.ServiceNo, "IX_ServiceNoInfo")
                    .IsUnique();

                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.BookId).HasColumnName("book_id");

                entity.Property(e => e.Description)
                    .HasMaxLength(50)
                    .IsUnicode(false)
                    .HasColumnName("description");

                entity.Property(e => e.PpRate)
                    .HasColumnType("decimal(8, 4)")
                    .HasColumnName("pp_rate");

                entity.Property(e => e.PsTotalKwp)
                    .HasColumnType("decimal(10, 3)")
                    .HasColumnName("ps_total_kwp");

                entity.Property(e => e.ServiceNo)
                    .IsRequired()
                    .HasMaxLength(20)
                    .IsUnicode(false)
                    .HasColumnName("service_no");

                entity.HasOne(d => d.Book)
                    .WithMany(p => p.ServiceNoInfo)
                    .HasForeignKey(d => d.BookId)
                    .OnDelete(DeleteBehavior.ClientSetNull)
                    .HasConstraintName("FK_ServiceNoInfo_set_of_books");
            });

            modelBuilder.Entity<SetOfBooks>(entity =>
            {
                entity.HasKey(e => e.BookId);

                entity.ToTable("set_of_books");

                entity.Property(e => e.BookId)
                    .ValueGeneratedNever()
                    .HasColumnName("book_id");

                entity.Property(e => e.Description)
                    .HasMaxLength(250)
                    .IsUnicode(false)
                    .HasColumnName("description");

                entity.Property(e => e.Name)
                    .IsRequired()
                    .HasMaxLength(100)
                    .IsUnicode(false)
                    .HasColumnName("name");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}