// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEPV_Api.Models.GreenPower
{
    public partial class LoginRoles
    {
        public LoginRoles()
        {
            LoginInfoRoles = new HashSet<LoginInfoRoles>();
            LoginRolesMenus = new HashSet<LoginRolesMenus>();
            ProjectPlm = new HashSet<ProjectPlm>();
        }

        public int Id { get; set; }
        public string RoleName { get; set; }
        public string Description { get; set; }
        public bool Disabled { get; set; }
        public short BookId { get; set; }
        public bool IsAdmin { get; set; }
        public byte PermissionLevel { get; set; }

        public virtual SetOfBooks Book { get; set; }
        public virtual ICollection<LoginInfoRoles> LoginInfoRoles { get; set; }
        public virtual ICollection<LoginRolesMenus> LoginRolesMenus { get; set; }
        public virtual ICollection<ProjectPlm> ProjectPlm { get; set; }
    }
}