// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEPV_Api.Models.GreenPower
{
    public partial class PpbasicInfo
    {
        public PpbasicInfo()
        {
            PppowerNoInfo = new HashSet<PppowerNoInfo>();
        }

        public int Id { get; set; }
        public short BookId { get; set; }
        public string PpNo { get; set; }
        public string PpName { get; set; }
        public int? TaxIdNo { get; set; }
        public string Telephone { get; set; }
        public string Contact { get; set; }
        public string Description { get; set; }
        public string Ctype { get; set; }

        public virtual SetOfBooks Book { get; set; }
        public virtual ICollection<PppowerNoInfo> PppowerNoInfo { get; set; }
    }
}