// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEPV_Api.Models.GreenPower
{
    public partial class PpmeterNoInfo
    {
        public PpmeterNoInfo()
        {
            ServiceNoDetailInfo = new HashSet<ServiceNoDetailInfo>();
        }

        public int Id { get; set; }
        public string MeterNo { get; set; }
        public string Description { get; set; }
        public int PpId { get; set; }

        public virtual PppowerNoInfo Pp { get; set; }
        public virtual ICollection<ServiceNoDetailInfo> ServiceNoDetailInfo { get; set; }
    }
}