// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEPV_Api.Models.GreenPower
{
    public partial class PppowerNoInfo
    {
        public PppowerNoInfo()
        {
            PpmeterNoInfo = new HashSet<PpmeterNoInfo>();
        }

        public int Id { get; set; }
        public string PowerNo { get; set; }
        public string Description { get; set; }
        public int? InfoId { get; set; }

        public virtual PpbasicInfo Info { get; set; }
        public virtual ICollection<PpmeterNoInfo> PpmeterNoInfo { get; set; }
    }
}