// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEPV_Api.Models.GreenPower
{
    public partial class ProjectPlm
    {
        public int Id { get; set; }
        public int? Year { get; set; }
        public string Quarter { get; set; }
        public int? Month { get; set; }
        public DateTime? CloseDate { get; set; }
        public decimal? RfqToClientAmount { get; set; }
        public decimal? NetToDsAmount { get; set; }
        public string SystemInquiryChannel { get; set; }
        public string IsSystemChecked { get; set; }
        public bool? IsAgsBooking { get; set; }
        public int? CustomerId { get; set; }
        public string IndustryCrm { get; set; }
        public string ExistingPlm { get; set; }
        public string ExistingCad { get; set; }
        public string AgsStatus { get; set; }
        public string UnderControlLongshotYearQ { get; set; }
        public string SolutionMapping { get; set; }
        public string SalesOwner { get; set; }
        public string ServiceOwner { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? UpdatedAt { get; set; }

        public virtual CustomerPlm Customer { get; set; }
    }
}