// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEPV_Api.Models.GreenPower
{
    public partial class PsbankData
    {
        public PsbankData()
        {
            PspowerNoInfo = new HashSet<PspowerNoInfo>();
        }

        public int Id { get; set; }
        public int InfoId { get; set; }
        public int BranchId { get; set; }
        public string BankAccountNumber { get; set; }
        public string Description { get; set; }

        public virtual BankBranchInfo Branch { get; set; }
        public virtual PsbasicInfo Info { get; set; }
        public virtual ICollection<PspowerNoInfo> PspowerNoInfo { get; set; }
    }
}