// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEPV_Api.Models.GreenPower
{
    public partial class PsbasicInfo
    {
        public PsbasicInfo()
        {
            PsbankData = new HashSet<PsbankData>();
            PspowerNoInfo = new HashSet<PspowerNoInfo>();
        }

        public int Id { get; set; }
        public short BookId { get; set; }
        public string PsNo { get; set; }
        public string PsName { get; set; }
        public int? TaxIdNo { get; set; }
        public string Telephone { get; set; }
        public string Contact { get; set; }
        public string Description { get; set; }
        public string Email { get; set; }

        public virtual SetOfBooks Book { get; set; }
        public virtual ICollection<PsbankData> PsbankData { get; set; }
        public virtual ICollection<PspowerNoInfo> PspowerNoInfo { get; set; }
    }
}