// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEPV_Api.Models.GreenPower
{
    public partial class PspowerNoInfo
    {
        public PspowerNoInfo()
        {
            PsmeterNoInfo = new HashSet<PsmeterNoInfo>();
            PssurplusInfo = new HashSet<PssurplusInfo>();
        }

        public int Id { get; set; }
        public string PowerNo { get; set; }
        public string Description { get; set; }
        public int? InfoId { get; set; }
        public string Etype { get; set; }
        public string SiteName { get; set; }
        public string Address { get; set; }
        public int? PsBankId { get; set; }
        public int? TrustBankId { get; set; }

        public virtual PsbasicInfo Info { get; set; }
        public virtual PsbankData PsBank { get; set; }
        public virtual BankInfo TrustBank { get; set; }
        public virtual ICollection<PsmeterNoInfo> PsmeterNoInfo { get; set; }
        public virtual ICollection<PssurplusInfo> PssurplusInfo { get; set; }
    }
}