// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEPV_Api.Models.GreenPower
{
    public partial class PssurplusInfo
    {
        public PssurplusInfo()
        {
            PssurplusData = new HashSet<PssurplusData>();
        }

        public int Id { get; set; }
        public string PsSiteName { get; set; }
        public decimal SurplusRate { get; set; }
        public string Description { get; set; }
        public decimal? TotalKwp { get; set; }
        public int PsId { get; set; }

        public virtual PspowerNoInfo Ps { get; set; }
        public virtual ICollection<PssurplusData> PssurplusData { get; set; }
    }
}