// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEPV_Api.Models.GreenPower
{
    public partial class PssurplusData
    {
        public int Id { get; set; }
        public short BillYear { get; set; }
        public byte BillMonth { get; set; }
        public int? SurplusKwh { get; set; }
        public int SurplusAmount { get; set; }
        public string Description { get; set; }
        public int SurplusId { get; set; }

        public virtual PssurplusInfo Surplus { get; set; }
    }
}