// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEPV_Api.Models.GreenPower
{
    public partial class ServiceNoInfo
    {
        public ServiceNoInfo()
        {
            ServiceNoDetailInfo = new HashSet<ServiceNoDetailInfo>();
        }

        public int Id { get; set; }
        public short BookId { get; set; }
        public string ServiceNo { get; set; }
        public decimal? PsTotalKwp { get; set; }
        public decimal? PpRate { get; set; }
        public string Description { get; set; }

        public virtual SetOfBooks Book { get; set; }
        public virtual ICollection<ServiceNoDetailInfo> ServiceNoDetailInfo { get; set; }
    }
}