// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEPV_Api.Models.GreenPower
{
    public partial class ServiceNoDetailData
    {
        public int Id { get; set; }
        public int ServiceNoDetailId { get; set; }
        public short BillYear { get; set; }
        public byte BillMonth { get; set; }
        public int KwhUsage { get; set; }
        public decimal TransmissionRate { get; set; }
        public decimal DistributionRate { get; set; }
        public decimal DispatchingRate { get; set; }
        public decimal AncillaryServicesRate { get; set; }
        public int Fee { get; set; }
        public string Description { get; set; }

        public virtual ServiceNoDetailInfo ServiceNoDetail { get; set; }
    }
}