// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEPV_Api.Models.GreenPower
{
    public partial class ServiceNoDetailInfo
    {
        public ServiceNoDetailInfo()
        {
            ServiceNoDetailData = new HashSet<ServiceNoDetailData>();
        }

        public int Id { get; set; }
        public int PsMeterId { get; set; }
        public int PpMeterId { get; set; }
        public string Description { get; set; }
        public int ServiceNoId { get; set; }
        public decimal? PsPpPercent { get; set; }
        public decimal? PsRate { get; set; }
        public decimal? PsTotalKwp { get; set; }
        public string Type { get; set; }

        public virtual PpmeterNoInfo PpMeter { get; set; }
        public virtual PsmeterNoInfo PsMeter { get; set; }
        public virtual ServiceNoInfo ServiceNo { get; set; }
        public virtual ICollection<ServiceNoDetailData> ServiceNoDetailData { get; set; }
    }
}