// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SEPV_Api.Models.GreenPower
{
    public partial class SetOfBooks
    {
        public SetOfBooks()
        {
            LoginInfo = new HashSet<LoginInfo>();
            LoginRoles = new HashSet<LoginRoles>();
        }

        public short BookId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }

        public virtual ICollection<LoginInfo> LoginInfo { get; set; }
        public virtual ICollection<LoginRoles> LoginRoles { get; set; }
    }
}